# Docker Compose para ambiente Green
version: '3.8'

services:
  frontend-green:
    image: ghcr.io/alucardponce/frontint:${IMAGE_TAG:-latest}
    container_name: frontend-green
    ports:
      - "8082:80"
    restart: unless-stopped
    networks:
      - bluegreen

  backend-green:
    image: ghcr.io/alucardponce/backint:${IMAGE_TAG:-latest}
    container_name: backend-green
    ports:
      - "3002:3000"
    restart: unless-stopped
    networks:
      - bluegreen

networks:
  bluegreen:
    name: bluegreen
    driver: bridge