# Docker Compose para ambiente Blue
version: '3.8'

services:
  frontend-blue:
    image: ghcr.io/alucardponce/frontint:${IMAGE_TAG:-latest}
    container_name: frontend-blue
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - bluegreen

  backend-blue:
    image: ghcr.io/alucardponce/backint:${IMAGE_TAG:-latest}
    container_name: backend-blue
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - bluegreen

networks:
  bluegreen:
    name: bluegreen
    driver: bridge